### ISSUE TITLE
plan stops working

### ISSUE THREAD

**Issue by zhous** [BlockIo/block_io-php#10]
I'm sorry but I haven't got any response from the support email box of block.io. Also I haven't never got the phone through.
Please give me a reply by sending me an email to zhous1998@gmail.com and 3ewebweb@gmail.com, or just call my mobile: 0086 159 996 224 68. I'm in Shenzhen China.
Thank you!
Derek

**Comment by RishabSwift** [comment]
It sucks that you have gotten no response. The support is absolutely horrible. BlockIo does not care about their developers from whom they are making money off.

 I'm afraid you are stuck on your own.
