### ISSUE TITLE
Enforcing TLSv1 necessary?

### ISSUE THREAD

**Issue by l0rb** [BlockIo/block_io-php#11]
[Line 104](https://github.com/BlockIo/block_io-php/blob/master/lib/block_io.php#L104) enforces TLSv1 via CURLOPT_SSL_CIPHER_LIST. Is this really necessary? At least TLSv1.2 should be allowed.

**Comment by doersf** [comment]
We've updated this to enforce TLSv1.2 going forward. TLSv1.0 is supported for at least 90 more days at Block.io, however.

Thanks!
