### ISSUE TITLE
mrypt functions are deprecated

### ISSUE THREAD

**Issue by RishabSwift** [BlockIo/block_io-php#13]
While withdrawing money, I'm getting an exception.

> ErrorException in block_io.php line 303:Function mcrypt_decrypt() is deprecated

Using PHP 7.0. Please fix this!

Maybe openssl_encrypt would be a better choice.

**Comment by RishabSwift** [comment]
Any update on a fix? I've been using Curl for now

**Comment by doersf** [comment]
We're looking into this. In the mean time, use an earlier version of PHP.

**Comment by RishabSwift** [comment]
I am using curl in the mean time. I cannot use an earlier version of PHP for various reasons. Maybe put on the docs that this does not work with 7.0?
