### ISSUE TITLE
Transaction Fees even in testnet

### ISSUE THREAD

**Issue by RishabSwift** [BlockIo/block_io-php#14]
I have a testnet address with `0.00078 BTC`. 

When I try to withdraw this to another testnet address, I get this error:

> Withdrawal amount cannot exceed -0.00057 ฿T due to mandatory network fees. Estimated network fee: 0.00135 ฿T

This makes it impossible to withdraw it. Please fix this. Thanks.

**Comment by doersf** [comment]
Hi, please treat this error as "cannot exceed 0.00000" instead. The bottom line is: the network fees will be higher than what you have in the wallet.

This will be fixed in the near future, not a priority.

**Comment by warayut21** [comment]
ok
