### ISSUE TITLE
create invoice

### ISSUE THREAD

**Issue by tomanexchange** [BlockIo/block_io-php#19]
Kamran,

I sent's lots of emails to support to ask this question but it seems block.io do not answer any emails, so i decided to ask it here.
how is it possible to use block.io to create new address for each invoice we create to receive payment?

Best Regards,

**Comment by doersf** [comment]
1) Create a new address whenever you create an invoice.
2) Use it.

Invoicing isn't related to what Block.io offers. You do the invoices yourself.

**Comment by tomanexchange** [comment]
Hello,

I know that we have to create address whenever we want to create invoice!
but the plans on the block.io website is limited to created address,
so if an exchange website wants to receive  money from customers it can just accept 2500 transactions for his life which is not reasonable, the advantage of an crypto currency is the make them anonymous and we want to keep this advantage. please give me the solution 
i want to know maybe there is other solution for such an action?

Best Regards,
