### ISSUE TITLE
hex2bin(): Hexadecimal input string must have an even length

### ISSUE THREAD

**Issue by kravchenkomaximus** [BlockIo/block_io-php#23]
I'm using lib/block_io.php and catch exception "hex2bin(): Hexadecimal input string must have an even length" during $block_io->withdraw_from_labels

Exception point:  $hashed = hash('sha256', hex2bin($pp));
In method: fromPassphrase($pp)

What I have to do?

**Comment by doersf** [comment]
Can you specify the version of PHP you're using?

**Comment by kravchenkomaximus** [comment]
PHP Version 7.1.12

**Comment by doersf** [comment]
This most likely has to do with specifics of your parameters. I see you've opened a support ticket for this; we'll handle it there.

**Comment by kravchenkomaximus** [comment]
What parameters should I provide for solve this trouble?

**Comment by kravchenkomaximus** [comment]
k
