### ISSUE TITLE
amount parameter in create request

### ISSUE THREAD

**Issue by saqlain-syed** [BlockIo/block_io-php#27]
Hi, I am working on your API and I am having a problem to understand the flow. 
I have used the create request and it is not accepting `amount` parameter. 
Can you please let me know how will we send the amount with `to_address` parameter in the following code ? and how this transaction will be proceed ?

$apiKey = "-----------";
$pin = "--------";
$version = 2; // the API version to use

$block_io = new BlockIo($apiKey, $pin, $version);

$response = $block_io->create_forwarding_address(array('to_address' => '----------' ));

**Comment by doersf** [comment]
Forwarding addresses don't need amounts to be specified. Anything you send to that address gets forwarded to the to_address you specify, as long as the amount is high enough to handle appropriate network fees.

**Comment by saqlain-syed** [comment]
Ok got It.. I have configured it on my localhost successfully last night and when I uploaded it on my live server, it showed an error that `GMP_Extension` is not installed on my server.. I have contacted to my service providers and installed this exntension, and they have said that exntension has been installed... but unfortunately, I am still getting the same error... Is the `gmp` was not installed properly or I've missed something else ? please guide me
thanks
