### ISSUE TITLE
Problem with withdraw

### ISSUE THREAD

**Issue by ABPSoft** [BlockIo/block_io-php#29]
Hi
I wrote a sample code for withdrawing.
It's work for 3 months.
But it doesn't work today!
I get this error!

Please guide me.
Thanks

{
    "status": "fail",
    "data": {
        "error_message": "Please use client-side signatures for this request. You can use our official PHP/Ruby/NodeJS/Python libraries; see block.io/api."
    }
}

**Comment by prinick96** [comment]
I have the same problem.

**Comment by doersf** [comment]
How're you executing the failed requests? Specify the parameters you're using. Do not specify values.

**Comment by prinick96** [comment]
$block_io->withdraw(array('amounts' => 'AMOUNT1,AMOUNT2,...', 'to_addresses' => 'ADDRESS1,ADDRESS2,...'));

@doersf

**Comment by doersf** [comment]
@prinick96 you were most likely adding a "pin" to that call, which isn't necessary.
