### ISSUE TITLE
Forwarding addresses can't be created directly, but you can create keys yourself and manage your forwarding mechanism via the WebHooks instead.

### ISSUE THREAD

**Issue by ABPSoft** [BlockIo/block_io-php#31]
How can I do it? Where is the document?

I bought you "The Diver" package to use this facility.

Forwarding addresses can't be created directly, but you can create keys yourself and manage your forwarding mechanism via the WebHooks instead.

_Originally posted by @doersf in https://github.com/BlockIo/block_io-php/issues/30#issuecomment-492092634_

**Comment by doersf** [comment]
Hi, please use block.io/contacts for this. You can always request a refund of the appropriate payment if you no longer need the services offered.
