### ISSUE TITLE
Withdraw problem

### ISSUE THREAD

**Issue by prinick96** [BlockIo/block_io-php#33]
Failed: Please use our official PHP/Ruby/NodeJS/Python libraries to make this request; see block.io/api. Do not provide PINs in your requests, and make sure you're using the current versions of the libraries.

The system has been running for 9 months without problem, today began this problem when they try to withdraw.

I DON'T send any PIN.

**Comment by doersf** [comment]
This won't happen unless you're inadvertently passing the PIN parameter. Use block.io/contacts so support can help you identify your issue.
