### ISSUE TITLE
create_forwarding_address

### ISSUE THREAD

**Issue by hamedtorky** [BlockIo/block_io-php#34]
Hi I'm using your API, though this method is not available unfortunately ,I've got other issues and i can not find any solution for substitute `create_forwarding_address` . could u please explain another way with an example ?

**Comment by doersf** [comment]
You'll want to create your own:

* Create an address using any appropriate Bitcoin library, store its private key for later use
* Create a web hook notification for that address
* Whenever you receive incoming fund notifications via web hook, except the `sweep_from_address` method of this library (look at its code)

That's all for forwarding mechanisms.
