### ISSUE TITLE
Getting Error : Fatal error: Uncaught Error: Class 'BlockIo\Exception' not found in 

### ISSUE THREAD

**Issue by Nilsxcoins** [BlockIo/block_io-php#43]
Hi,
i am getting this error 

when calling get get_balance()

`Fatal error: Uncaught Error: Class 'BlockIo\Exception' not found in C:\xampp\htdocs\project\vendor\block_io-php\block_io-php\lib\Client.php:96 Stack trace: #0 C:\xampp\htdocs\project\vendor\block_io-php\block_io-php\lib\Client.php(74): BlockIo\Client->_request('get_balance', Array) #1 C:\xampp\htdocs\project\cron\test.php(19): BlockIo\Client->__call('get_balance', Array) #2 {main} thrown in C:\xampp\htdocs\project\vendor\block_io-php\block_io-php\lib\Client.php on line 96`

**Comment by doersf** [comment]
Here's the error: https://github.com/BlockIo/block_io-php/blob/master/lib/Client.php#L96

You will want to download the cacert.pem as indicated in that error. This will be patched in 24 hours in the next minor release.

**Comment by doersf** [comment]
Fixed in https://github.com/BlockIo/block_io-php/releases/tag/2.0.1.
