### ISSUE TITLE
COMPOSER : block_io-php/block_io-php require bitwasp/bitcoin dev-minimal

### ISSUE THREAD

**Issue by StudiosKelemy** [BlockIo/block_io-php#44]
Hi, 
There is a problemen when installing this package with composer : 
COMPOSER : block_io-php/block_io-php require bitwasp/bitcoin dev-minimal

any issue for this. Thanks

**Comment by doersf** [comment]
See https://github.com/BlockIo/block_io-php/blob/master/README.md.

```{
    "require":{
	"block_io-php/block_io-php": "2.0.2",
	"bitwasp/bitcoin": "dev-minimal"
    },
    "repositories": [
        {
            "type": "git",
            "url": "https://github.com/doersf/bitcoin-php.git"
        }
    ]
}```
