### ISSUE TITLE
Installation Fails; Require "bitwasp/bitcoin dev-minimal" throws an error

### ISSUE THREAD

**Issue by nensamuel** [BlockIo/block_io-php#45]
When installing this package via composer, this error pops up

`Problem 1
    - block_io-php/block_io-php[2.0.0, ..., 2.0.2] require bitwasp/bitcoin dev-minimal -> found bitwasp/bitcoin[dev-master, 0.0.1, ..., 0.0.35.x-dev, v1.0.0, ..., 1.0.x-dev] but it does not match the constraint.
    - Root composer.json requires block_io-php/block_io-php ^2.0 -> satisfiable by block_io-php/block_io-php[2.0.0, 2.0.1, 2.0.2].
`

After this error persisted, I went ahead to install "bitwasp/bitcoin dev-master" and then tried installing blockio, but the same requirements made the installation fail. I am currently stuck here and everyone else trying to install might also get stuck

My device is running on PHP 7.4, MacOS 10.15.7 Catalina

**Comment by doersf** [comment]
You need to use the appropriate github repository to get this branch. See below, as shown in [README](https://github.com/BlockIo/block_io-php/blob/master/README.md)

```
{
    "require":{
	"block_io-php/block_io-php": "2.0.2",
	"bitwasp/bitcoin": "dev-minimal"
    },
    "repositories": [
        {
            "type": "git",
            "url": "https://github.com/doersf/bitcoin-php.git"
        }
    ]
}
```

**Comment by nensamuel** [comment]
After adding the repo, it was installed properly. Thanks for the heads up
