### ISSUE TITLE
Invalid bitwasp/bitcoin version specified in composer.json

### ISSUE THREAD

**Issue by calcifer1337** [BlockIo/block_io-php#46]
When trying to require this package the following error is thrown:

` Problem 1
    - block_io-php/block_io-php[2.0.0, ..., 2.0.2] require bitwasp/bitcoin dev-minimal -> found bitwasp/bitcoin[dev-master, 0.0.1, ..., 0.0.35.x-dev, v1.0.0, ..., 1.0.x-dev] but it does not match the constraint.
    - Root composer.json requires block_io-php/block_io-php ^2.0 -> satisfiable by block_io-php/block_io-php[2.0.0, 2.0.1, 2.0.2].`

**Comment by doersf** [comment]
bitwasp/bitcoin-php is largely unmaintained rightnow. You're asked to use github.com/doersf/bitcoin-php. See README.md.
