### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by artytech1** [BlockIo/block_io-php#47]
Hi how do i get this package working in Laravel?
Problem 1
    - block_io-php/block_io-php[2.0.0, ..., 2.0.2] require bitwasp/bitcoin dev-minimal -> found bitwasp/bitcoin[dev-master, 0.0.1, ..., 0.0.35.x-dev, v1.0.0, ..., 1.0.x-dev] but it does not match the constraint.
    - Root composer.json requires block_io-php/block_io-php ^2.0 -> satisfiable by block_io-php/block_io-php[2.0.0, 2.0.1, 2.0.2].

I couldn't install bitwasp either conflicts with other packages and my php version 8.
any suggestions? Thanks!

**Comment by artytech1** [comment]
hi no need for help, finally  got package working myself thanks

**Comment by doersf** [comment]
The bitwasp/bitcoin package is unmaintained for the time being, so you're asked to use github.com/doersf/bitcoin-php instead. See README.md.
