### ISSUE TITLE
Fatal error: Uncaught exception 'Exception' with message 'Failed: '...

### ISSUE THREAD

**Issue by zerogods** [BlockIo/block_io-php#5]
Maybe I'm doing something wrong?? 
Here's my code.. 

```
require_once '../libs/block_io.php'; //Block.io API
$version = 2; // API version
$pin = getenv('BLOCKIOPIN'); //Block_io main pin 
// echo $pin; // OK
$apiKey = getenv('dogetestnet'); //DOGE testnet
// echo $apiKey; // OK
$block_io = new BlockIo($apiKey, $pin, $version);
$Address = $block_io->get_my_addresses();  //this is line 34 at blockio_test.php
```

RETURNS 

> Notice: Trying to get property of non-object in ../repo/libs/block_io.php on line 107 Notice: Trying to get property of non-object in ../repo/libs/block_io.php on line 107 Notice: Trying to get property of non-object in ../repo/libs/block_io.php on line 107 Fatal error: Uncaught exception 'Exception' with message 'Failed: ' in ../repo/libs/block_io.php:107 Stack trace: # 0 ../repo/libs/block_io.php(60): BlockIo->_request('get_my_addresse...', Array) # 1 ../repo/php/blockio_test.php(34): BlockIo->__call('get_my_addresse...', Array) # 2 ../repo/php/blockio_test.php(34): BlockIo->get_my_addresses() # 3 {main} thrown in ../repo/libs/block_io.php on line 107

**Comment by chitranjanmahto** [comment]
Fatal error: Uncaught Exception: GMP extension seems not to be installed in /homepages/33/d597612788/htdocs/kalamsite/ksm/libs/block_io.php:10 Stack trace: #0 /homepages/33/d597612788/htdocs/kalamsite/ksm/block.php(2): require_once() #1 {main} thrown in /homepages/33/d597612788/htdocs/kalamsite/ksm/libs/block_io.php on line 10
