### ISSUE TITLE
Queries regarding block_io payment processing.

### ISSUE THREAD

**Issue by bhaskar-pandit** [BlockIo/block_io-php#51]
Hey,

We want to process payment through another wallet to my block_io wallet. Is there any documentation for it? since we are trying to call `prepare_transaction` with another wallet address it's throwing some errors regarding `addresses not exist in account`. So can anyone please help me how can process payment?

**Comment by doersf** [comment]
The prepare_transaction endpoint is documented at https://block.io/api/simple/php. You cannot use external addresses with this endpoint- you will need to create an address within your Block.io account and then use it.

Regardless, this is a query, not an issue for this library. Use support@block.io.

**Comment by bhaskar-pandit** [comment]
is it possible to use this library to accept transactions outside the Block.io address?

Thanks,

**Comment by doersf** [comment]
You can sweep coins from external addresses, but that's it. Block.io is intended for multisig wallets. 

See examples/sweeper.php.

If you do not have an issue to report for this library, **do not** use Issues here.
