### ISSUE TITLE
Composer.json

### ISSUE THREAD

**Issue by MB190XS** [BlockIo/block_io-php#55]
Hello, i am receiving errors while composer update.

    - Root composer.json requires bitwasp/bitcoin dev-minimal, found bitwasp/bitcoin[dev-master, 0.0.1, ..., 0.0.35.x-dev, v1.0.0, ..., 1.0.x-dev] but it does not match the constraint.
  Problem 2
    - Root composer.json requires block_io-php/block_io-php 2.0.2 -> satisfiable by block_io-php/block_io-php[2.0.2].
    - block_io-php/block_io-php 2.0.2 requires bitwasp/bitcoin dev-minimal -> found bitwasp/bitcoin[dev-master, 0.0.1, ..., 0.0.35.x-dev, v1.0.0, ..., 1.0.x-dev] but it does not match the constraint.

I am using example of composer.json from your readme.md.
Any help is appreciated, (other guy had same problem and he solved it himself, there were no answers given or information about solution shared)

Using PHP 7.4

**Comment by doersf** [comment]
See https://github.com/BlockIo/block_io-php/blob/master/README.md. The composer.json needs to specify the location of the dev-minimal branch, which is in a separate repository (not the bit-wasp link).

**Comment by MB190XS** [comment]
> See https://github.com/BlockIo/block_io-php/blob/master/README.md. The composer.json needs to specify the location of the dev-minimal branch, which is in a separate repository (not the bit-wasp link).


My project's composer.json looks like this. Added repository aswell below require but somehow it doesnt use your fork.

`    "require": {
        "php": "^7.3|^8.0",
        "coingate/coingate-php": "^3.0",
        "ezyang/htmlpurifier": "^4.13",
        "fideloper/proxy": "^4.4",
        "fruitcake/laravel-cors": "^2.0",
        "guzzlehttp/guzzle": "^7.0.1",
        "intervention/image": "^2.5",
        "laravel/framework": "^8.12",
        "laravel/sanctum": "^2.11",
        "laravel/tinker": "^2.5",
        "laravel/ui": "^3.2",
        "mailjet/mailjet-apiv3-php": "^1.4",
        "messagebird/php-rest-api": "^1.20",
        "mollie/laravel-mollie": "^2.14",
        "phpmailer/phpmailer": "^6.2",
        "razorpay/razorpay": "^2.5",
        "sendgrid/sendgrid": "^7.6",
        "stripe/stripe-php": "^7.72",
        "textmagic/sdk": "dev-master",
        "twilio/sdk": "^6.23",
        "vonage/client": "^2.4",
        "bitwasp/bitcoin": "dev-minimal",
        "block_io-php/block_io-php": "2.0.2"
    },
    "repositories": [
        {
            "type": "git",
            "url": "https://github.com/doersf/bitcoin-php.git"
        }
    ],`
