### ISSUE TITLE
Force use of TLSv1 is not working

### ISSUE THREAD

**Issue by nch7** [BlockIo/block_io-php#6]
All the POST requests I'm trying to send end up with exception:
"An error occurred while validating SSL connectivity. Please make sure you are using TLSv1 or above."

I see curl is forced to use TLSv1 already but looks like this is not working. 

I'm testing on:
- Ubuntu 14.04
- PHP 5.6.13
- cURL 7.35.0

Can you please recommend me anything to solve this issue?

**Comment by patricklodder** [comment]
I'll have to discuss if we still need this to be enforced. I'll get back here once I know more.

For now, the workaround would be to remove the line that enforces TLSv1 at [`lib/block_io.php#L104`](https://github.com/BlockIo/block_io-php/blob/master/lib/block_io.php#L104) locally.

**Comment by nch7** [comment]
That doesn't help unfortunately, block.io API server returns an error if I don't use TLSv1 (same error: `An error occurred while validating SSL connectivity. Please make sure you are using TLSv1 or above.`)

I also tried to set `CURLOPT_SSLVERSION` to `CURL_SSLVERSION_TLSv1` but still no luck.

**Comment by patricklodder** [comment]
I've tried to reproduce this on an ubuntu 15.04 install but no luck there.

Before I start building a 14.04 box, could you please:
1. try setting `CURLOPT_SSL_CIPHER_LIST` to `'TLSv1.2'` and test if that works?
2. share the output of `openssl version`
3. share the output of `dpkg-query -W -f '${db:Status-Abbrev}\t${Package}\t${Version}\n' ca-certificates`
4. did you compile php manually, used the packaged one from ubuntu or something else?

**Comment by nch7** [comment]
1. Same error
2. ` OpenSSL 1.0.1f 6 Jan 2014`
3. `ii 	ca-certificates	20141019ubuntu0.14.04.1`
4. I'm using Laravel Homestead (pre-packaged vagrant box), instructions are available here: http://laravel.com/docs/5.1/homestead , I also tested on http://digitalocean.com server deployed using http://forge.laravel.com

**Comment by doersf** [comment]
@nch7 when you create notification, your server needs to use TLSv1 or higher if you specify an HTTPS URL. The error tells you it's having trouble with SSL on your Webhook URL, and therefore cannot verify it as a valid URL to which it can push Webhook notifications.

Here's something help you check your SSL installation and ciphers used: https://www.ssllabs.com/ssltest/.

**Comment by nch7** [comment]
Thanks for the hint @doersf problem is resolved
